name: Discord Commits

on: [push]

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Commits
      uses: Sniddl/discord-commits@v1.3
      with:
        webhook: ${{ secrets.WEBHOOK_URL }}
        message: "** {{ github.context.payload.repository.owner.name }}/{{ github.context.payload.repository.name}} **"
        embed: '{"title": "{{ github.context.payload.repository.name }}","description": "{{ commit.title}}\n{{ commit.description  }}","url": "{{ commit.url }}","author": {"name": "{{ commit.author.name }} ({{ commit.author.username }})","icon_url": "https://avatars.githubusercontent.com/{{ commit.author.username }}"},"footer": {"text": "KINGMAN KMCODES","icon_url": "{{ github.context.payload.repository.owner.avatar_url }}"}}'
        last-commit-only: false
